language: generic
sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t cainuse/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cainuse/react-test npm test

after_success:
  # Log in to the docker CLI
  # Retrieve dockerpassword from stdout and pipe that to the stdin to docker login command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t cainuse/multi-client ./client
  - docker build -t cainuse/multi-nginx ./nginx
  - docker build -t cainuse/multi-server ./server
  - docker build -t cainuse/multi-worker ./worker
  # Take those images and push them to docker hub
  - docker push cainuse/multi-client
  - docker push cainuse/multi-nginx
  - docker push cainuse/multi-server
  - docker push cainuse/multi-worker
